<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.ycr.framework</groupId>
        <artifactId>ycr-framework</artifactId>
        <version>${revision}</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>

    <artifactId>ycr-starter-data</artifactId>
    <packaging>pom</packaging>
    <name>YCR Starter Data</name>
    <description>数据访问基础模块 - 分页、查询条件、基础实体</description>

    <modules>
        <module>ycr-starter-data-core</module>
        <module>ycr-starter-data-mp</module>
    </modules>
</project>
